@host=https://localhost:7109
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwN2JjNzg5My0xNGZiLTRiNmMtOTQzYy00NWU1ZTYwNTgxNTgiLCJnaXZlbl9uYW1lIjoiRnVsYW5vIiwiZmFtaWx5X25hbWUiOiJEZXRhbCIsImp0aSI6IjZhMjA5OWNhLWM5ZmMtNGMxMC1hOWY0LWM5ZjRiZDMzNTYxOCIsImV4cCI6MTY4OTAyNjIxNiwiaXNzIjoiSG9ybmVyb0NsZWFuIiwiYXVkIjoiSG9ybmVyb0NsZWFuIn0.DCI9Dgw7huuDfz-ZeU68SkyjTsRhNm1FwAkEte3OvHE