@host=https://localhost:7109
POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "Fulano",
    "LastName": "Detal",
    "Email": "fulanodetal@email.com",
    "Password": "1Abcdef!"
}